### ISSUE TITLE
cp: cannot create regular file '/bitnami/postgresql/conf/postgresql.conf': Read-only file system

### ISSUE THREAD

**Issue by suhaibqaiser** [bitnami/bitnami-docker-postgresql-repmgr#116]
### Name and Version

bitnami/postgresql-repmgr:12

### What steps will reproduce the bug?

1. In Kubernetes
2. Deploying stateless postgres HA with pgpool
3. Trying to apply custom config "sharedBuffer" through configmap
4. It is failing to mount volume to bitnami/postgres/config giving error

### What is the expected behavior?

sharedBuffer value should be applied to postgress config

### What do you see instead?
```
[38;5;6mpostgresql-repmgr [38;5;5m22:09:19.98 [0m
[38;5;6mpostgresql-repmgr [38;5;5m22:09:19.98 [0m[1mWelcome to the Bitnami postgresql-repmgr container[0m
[38;5;6mpostgresql-repmgr [38;5;5m22:09:19.98 [0mSubscribe to project updates by watching [1mhttps://github.com/bitnami/bitnami-docker-postgresql-repmgr[0m
[38;5;6mpostgresql-repmgr [38;5;5m22:09:19.98 [0mSubmit issues and feature requests at [1mhttps://github.com/bitnami/bitnami-docker-postgresql-repmgr/issues[0m
[38;5;6mpostgresql-repmgr [38;5;5m22:09:19.98 [0m
[38;5;6mpostgresql-repmgr [38;5;5m22:09:20.00 [0m[38;5;2mINFO [0m ==> ** Starting PostgreSQL with Replication Manager setup **
[38;5;6mpostgresql-repmgr [38;5;5m22:09:20.03 [0m[38;5;2mINFO [0m ==> Validating settings in REPMGR_* env vars...
[38;5;6mpostgresql-repmgr [38;5;5m22:09:20.03 [0m[38;5;2mINFO [0m ==> Validating settings in POSTGRESQL_* env vars..
[38;5;6mpostgresql-repmgr [38;5;5m22:09:20.03 [0m[38;5;2mINFO [0m ==> Querying all partner nodes for common upstream node...
[38;5;6mpostgresql-repmgr [38;5;5m22:09:20.08 [0m[38;5;2mINFO [0m ==> There are no nodes with primary role. Assuming the primary role...
[38;5;6mpostgresql-repmgr [38;5;5m22:09:20.09 [0m[38;5;2mINFO [0m ==> Preparing PostgreSQL configuration...
[38;5;6mpostgresql-repmgr [38;5;5m22:09:20.10 [0m[38;5;2mINFO [0m ==> postgresql.conf file not detected. Generating it...
cp: cannot create regular file '/bitnami/postgresql/conf/postgresql.conf': Read-only file system
```
### Additional information

I have tried using extendedconfig as well as postgres config. Here is the yaml configuration. Need to understand what is wrong here.
```
          volumeMounts:
            - name: data
              mountPath: /bitnami/postgresql
            - name: hooks-scripts
              mountPath: /pre-stop.sh
              subPath: pre-stop.sh
            - name: postgres-config
              mountPath: /bitnami/postgresql/conf
      volumes:
        - name: hooks-scripts
          configMap:
            name: postgres-configmap
            defaultMode: 0755
        - name: postgres-config
          configMap:
            name: postgres-configmap
            defaultMode: 0755
```
