### ISSUE TITLE
How can I set custom entry in pg_hba.conf?

### ISSUE THREAD

**Issue by AkashRajvanshi** [bitnami/bitnami-docker-postgresql-repmgr#126]
### Name and Version

bitnami/postgresql-repmgr:12.11.0

### What steps will reproduce the bug?

As suggested, I create a dir with the correct config but when starting the container it remove my custom pg_hba.conf entry.

These are the steps I followed:

```console
$ mkdir -p pg_0_data/{conf,logs,repmgr}
$ mkdir -p pg_1_data/{conf,logs,repmgr}

$ cat > ./pg_0_data/conf/pg_hba.conf << EOT
host     all            repmgr    0.0.0.0/0    trust
host     repmgr         repmgr    0.0.0.0/0    trust
host     repmgr         repmgr    ::/0    trust
host     replication      repmgr    0.0.0.0/0    trust
host     replication      repmgr    ::/0    trust
#hostssl     all             all             0.0.0.0/0               cert
#hostssl     all             all             ::/0                    cert
host     all              all       0.0.0.0/0    trust
host     all              all       ::/0         trust
local    all              all                    trust
host    replication     all       0.0.0.0/0    trust  --> this entry i want to start backup from another container
EOT
```
same for pg_1_data
```console
$ sudo chgrp -R root ./pg_0_data/conf
$ sudo chmod -R g+rwX ./pg_0_data/conf
```
same for pg_1_data

`docker-compose.yml`
```yaml
version: '3.8'

services:
  pg-0:
    image: bitnami/postgresql-repmgr:12.11.0
    container_name: pg-0
    restart: always
    networks:
      - database
    ports:
      - 5400:5432
    volumes:
      - ./pg_0_data/conf/:/bitnami/postgresql/conf/
      - ./pg_0_data/repmgr/:/bitnami/repmgr/conf/
      - ./pg_0_data/logs/:/opt/bitnami/postgresql/logs/
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=
      - POSTGRESQL_DATABASE=test-db
      - REPMGR_PASSWORD=
      - REPMGR_PRIMARY_HOST=pg-0
      - REPMGR_PRIMARY_PORT=5432
      - REPMGR_PARTNER_NODES=pg-0,pg-1:5432
      - REPMGR_NODE_NAME=pg-0
      - REPMGR_NODE_NETWORK_NAME=pg-0
      - REPMGR_NODE_ID=1
      - REPMGR_LOG_LEVEL=DEBUG
      - REPMGR_PORT_NUMBER=5432
  pg-1:
    image: bitnami/postgresql-repmgr:12.11.0
    container_name: pg-1
    restart: always
    networks:
      - database
    ports:
      - 5401:5432
    volumes:
      - ./pg_1_data/conf/:/bitnami/postgresql/conf/
      - ./pg_1_data/repmgr/:/bitnami/repmgr/conf/
      - ./pg_1_data/logs:/opt/bitnami/postgresql/logs/
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=
      - POSTGRESQL_DATABASE=test-db
      - REPMGR_PASSWORD=
      - REPMGR_PRIMARY_HOST=pg-0
      - REPMGR_PRIMARY_PORT=5432
      - REPMGR_PARTNER_NODES=pg-0,pg-1:5432
      - REPMGR_NODE_NAME=pg-1
      - REPMGR_NODE_NETWORK_NAME=pg-1
      - REPMGR_NODE_ID=2
      - REPMGR_LOG_LEVEL=DEBUG
      - REPMGR_PORT_NUMBER=5432

networks:
  database:
    external: true
```

after starting the container it removes my manual entry from pg_hba.conf

### What is the expected behavior?

after starting the container it will persist my entry in pg_hba.conf

### What do you see instead?

after starting the container it removes my manual entry from pg_hba.conf
