### ISSUE TITLE
Bitnami-docker-postgresql-repmgr:11 cant install packages

### ISSUE THREAD

**Issue by batchenr** [bitnami/bitnami-docker-postgresql-repmgr#2]
I'm  using image bitnami-docker-postgresql-repmgr:11 
and I need to build from my Dockerfile as I use an existing database for the replication, these commands don't work :

```bash
apt-get update -y
apt-get install postgis -y
```
I get the error:
```
E: List directory /var/lib/apt/lists/partial is missing. - Acquire (2: No such file or directory)
```
If i try to `mkdir -p /var/lib/apt/lists/partial` from Dockerfile I get the error
```
mkdir: cannot create directory ‘/var/lib/apt/lists’: Permission denied
```
what can I do?

I have to install PostGIS extension for my existing database.

my DockerFile:
```Dockerfile
FROM bitnami/postgresql-repmgr:11
COPY ./cluster/somrsql.sql /docker-entrypoint-initdb.d/somsql.sql
RUN apt-get install postgis -y
RUN apt-get update -y
```
my YML :
```yaml
version: '3'
services:

        db:
                image: 127.0.0.1:5000/bitnami/postgresql-repmgr:11
                build: docker-compose.d/postgres
                ports:
                - 5432
                volumes:
                - /db_data:/bitnami/postgresql
                environment:
                - POSTGRESQL_POSTGRES_PASSWORD=adminpassword
                - POSTGRESQL_USERNAME=user
                - POSTGRESQL_PASSWORD=password
                - POSTGRESQL_DATABASE=user
                - REPMGR_PASSWORD=repmgrpassword
                - REPMGR_PRIMARY_HOST=db
                - REPMGR_PARTNER_NODES=db,db-slave1
                - REPMGR_NODE_NAME=db
                - REPMGR_NODE_NETWORK_NAME=db

```
The only way I can install PostGIS with root is if I add  to the yml 
```yaml
                user: root
                privileged: true
```
but then it makes another issue. please make it easier to install psql extentions and packages.
thank you
