### ISSUE TITLE
Container immediately errors with code (6)

### ISSUE THREAD

**Issue by FatalCatharsis** [bitnami/bitnami-docker-postgresql-repmgr#34]
**Description**

When I start the container, I always get error code 6. Assuming that error code is actually repmgr, that tells me that it had trouble connecting to postgresql within the container? Without more diagnostic info, I don't really know where to go from here...

My compose service looks like this:

```
  pg-0:
    image: bitnami/postgresql-repmgr:12.4.0
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD_FILE=/run/secrets/postgres_root_password
      - REPMGR_PASSWORD_FILE=/run/secrets/repmgr_password
      - POSTGRESQL_USERNAME=IA
      - POSTGRESQL_PASSWORD_FILE=/run/secrets/postgres_password
      - REPMGR_PRIMARY_HOST=pg-0
      - REPMGR_PARTNER_NODES=pg-0
      - REPMGR_NODE_NAME=pg-0
      - REPMGR_NODE_NETWORK_NAME=pg-0
      - REPMGR_LOG_LEVEL=DEBUG
    ports:
      - 5433:5432
    volumes:
      - pg0data:/var/lib/postgresql
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - "node.hostname == IA1"
    secrets:
      - postgres_root_password
      - postgres_password
      - repmgr_password
```
Log result of docker-compose up pg-0:
```
Recreating prod-configs_pg-0_1 ... done                                                                                                          Attaching to prod-configs_pg-0_1
pg-0_1  | postgresql-repmgr 08:01:22.53
pg-0_1  | postgresql-repmgr 08:01:22.53 Welcome to the Bitnami postgresql-repmgr container
pg-0_1  | postgresql-repmgr 08:01:22.53 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql-repmgr
pg-0_1  | postgresql-repmgr 08:01:22.54 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql-repmgr/issues
pg-0_1  | postgresql-repmgr 08:01:22.54
pg-0_1  | postgresql-repmgr 08:01:22.56 INFO  ==> ** Starting PostgreSQL with Replication Manager setup **
pg-0_1  | postgresql-repmgr 08:01:22.58 INFO  ==> Validating settings in REPMGR_* env vars...
pg-0_1  | postgresql-repmgr 08:01:22.58 INFO  ==> Validating settings in POSTGRESQL_* env vars..
pg-0_1  | postgresql-repmgr 08:01:22.59 INFO  ==> Querying all partner nodes for common upstream node...
pg-0_1  | postgresql-repmgr 08:01:22.62 INFO  ==> There are no nodes with primary role. Assuming the primary role...
pg-0_1  | postgresql-repmgr 08:01:22.62 INFO  ==> Preparing PostgreSQL configuration...
pg-0_1  | postgresql-repmgr 08:01:22.63 INFO  ==> postgresql.conf file not detected. Generating it...
pg-0_1  | postgresql-repmgr 08:01:22.68 INFO  ==> Preparing repmgr configuration...
pg-0_1  | postgresql-repmgr 08:01:22.69 INFO  ==> Initializing Repmgr...
pg-0_1  | postgresql-repmgr 08:01:22.69 INFO  ==> Initializing PostgreSQL database...
pg-0_1  | postgresql-repmgr 08:01:22.70 INFO  ==> Custom configuration /opt/bitnami/postgresql/conf/postgresql.conf detected
pg-0_1  | postgresql-repmgr 08:01:22.70 INFO  ==> Custom configuration /opt/bitnami/postgresql/conf/pg_hba.conf detected
pg-0_1  | postgresql-repmgr 08:01:33.95 INFO  ==> Starting PostgreSQL in background...
pg-0_1  | postgresql-repmgr 08:01:34.08 INFO  ==> Changing password of postgres
pg-0_1  | postgresql-repmgr 08:01:34.11 INFO  ==> Creating user IA
pg-0_1  | postgresql-repmgr 08:01:34.12 INFO  ==> Granting access to "IA" to the database "postgres"
pg-0_1  | postgresql-repmgr 08:01:34.14 INFO  ==> Creating replication user repmgr
pg-0_1  | postgresql-repmgr 08:01:34.16 INFO  ==> Configuring replication parameters
pg-0_1  | postgresql-repmgr 08:01:34.17 INFO  ==> Configuring fsync
pg-0_1  | postgresql-repmgr 08:01:34.18 INFO  ==> Starting PostgreSQL in background...
pg-0_1  | postgresql-repmgr 08:01:34.18 INFO  ==> Creating repmgr user: repmgr
pg-0_1  | postgresql-repmgr 08:01:34.22 INFO  ==> Creating repmgr database: repmgr
pg-0_1  | postgresql-repmgr 08:01:36.89 INFO  ==> Stopping PostgreSQL...
pg-0_1  | postgresql-repmgr 08:01:37.89 INFO  ==> Starting PostgreSQL in background...
pg-0_1  | postgresql-repmgr 08:01:38.01 INFO  ==> Registering Primary...
pg-0_1  | postgresql-repmgr 08:01:38.02 INFO  ==> Stopping PostgreSQL...
prod-configs_pg-0_1 exited with code 6
```

**Steps to reproduce the issue:**

1) Make a compose file with the service above
2) Run `docker-compose up pg-0`

**Describe the results you received:**

Error code (6) on startup.

**Describe the results you expected:**

I expect it to start the db properly and be accessible on port 5433

**Additional information you deem important (e.g. issue happens only occasionally):**

Happens every time, at exactly the same point.

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:43:18 2020
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:49:27 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 9
  Running: 0
  Paused: 0
  Stopped: 9
 Images: 20
 Server Version: 19.03.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.76-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 1.945GiB
 Name: docker-desktop
 ID: 3WXQ:MFWQ:OOWZ:F7IU:YAHP:I5RQ:7PZN:3OZM:NIAK:3SXU:5HWS:FUFY
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 40
  Goroutines: 52
  System Time: 2020-09-06T08:14:07.409858979Z
  EventsListeners: 3
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
Windows 10

**Comment by FatalCatharsis** [comment]
After some fiddling around, it appears to be some issue with using the REPMGR_PASSWORD_FILE. When I switch that one to use REPMGR_PASSWORD and specify something else it loads properly.
```

  pg-0:
    image: bitnami/postgresql-repmgr:12.4.0
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD_FILE=/run/secrets/postgres_root_password
      - REPMGR_PASSWORD=abc123
      - POSTGRESQL_USERNAME=IA
      - POSTGRESQL_PASSWORD_FILE=/run/secrets/postgres_password
      - REPMGR_PRIMARY_HOST=pg-0
      - REPMGR_PARTNER_NODES=pg-0
      - REPMGR_NODE_NAME=pg-0
      - REPMGR_NODE_NETWORK_NAME=pg-0
      - REPMGR_LOG_LEVEL=DEBUG
    ports:
      - 5433:5432
    volumes:
      - pg0data:/var/lib/postgresql
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - "node.hostname == IA1"
    secrets:
      - postgres_root_password
      - postgres_password
      - repmgr_password
```
```
Attaching to prod-configs_pg-0_1
pg-0_1  | postgresql-repmgr 18:59:14.96
pg-0_1  | postgresql-repmgr 18:59:14.96 Welcome to the Bitnami postgresql-repmgr container
pg-0_1  | postgresql-repmgr 18:59:14.97 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql-repmgr
pg-0_1  | postgresql-repmgr 18:59:14.97 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql-repmgr/issues
pg-0_1  | postgresql-repmgr 18:59:14.97
pg-0_1  | postgresql-repmgr 18:59:14.99 INFO  ==> ** Starting PostgreSQL with Replication Manager setup **
pg-0_1  | postgresql-repmgr 18:59:15.02 INFO  ==> Validating settings in REPMGR_* env vars...
pg-0_1  | postgresql-repmgr 18:59:15.03 INFO  ==> Validating settings in POSTGRESQL_* env vars..
pg-0_1  | postgresql-repmgr 18:59:15.03 INFO  ==> Querying all partner nodes for common upstream node...
pg-0_1  | postgresql-repmgr 18:59:15.05 INFO  ==> There are no nodes with primary role. Assuming the primary role...
pg-0_1  | postgresql-repmgr 18:59:15.06 INFO  ==> Preparing PostgreSQL configuration...
pg-0_1  | postgresql-repmgr 18:59:15.06 INFO  ==> postgresql.conf file not detected. Generating it...
pg-0_1  | postgresql-repmgr 18:59:15.12 INFO  ==> Preparing repmgr configuration...
pg-0_1  | postgresql-repmgr 18:59:15.12 INFO  ==> Initializing Repmgr...
pg-0_1  | postgresql-repmgr 18:59:15.13 INFO  ==> Initializing PostgreSQL database...
pg-0_1  | postgresql-repmgr 18:59:15.13 INFO  ==> Custom configuration /opt/bitnami/postgresql/conf/postgresql.conf detected
pg-0_1  | postgresql-repmgr 18:59:15.13 INFO  ==> Custom configuration /opt/bitnami/postgresql/conf/pg_hba.conf detected
pg-0_1  | postgresql-repmgr 18:59:25.13 INFO  ==> Starting PostgreSQL in background...
pg-0_1  | postgresql-repmgr 18:59:25.35 INFO  ==> Changing password of postgres
pg-0_1  | postgresql-repmgr 18:59:25.36 INFO  ==> Creating user IA
pg-0_1  | postgresql-repmgr 18:59:25.37 INFO  ==> Granting access to "IA" to the database "postgres"
pg-0_1  | postgresql-repmgr 18:59:25.39 INFO  ==> Creating replication user repmgr
pg-0_1  | postgresql-repmgr 18:59:25.40 INFO  ==> Configuring replication parameters
pg-0_1  | postgresql-repmgr 18:59:25.42 INFO  ==> Configuring fsync
pg-0_1  | postgresql-repmgr 18:59:25.42 INFO  ==> Starting PostgreSQL in background...
pg-0_1  | postgresql-repmgr 18:59:25.43 INFO  ==> Creating repmgr user: repmgr
pg-0_1  | postgresql-repmgr 18:59:25.47 INFO  ==> Creating repmgr database: repmgr
pg-0_1  | postgresql-repmgr 18:59:28.91 INFO  ==> Stopping PostgreSQL...
pg-0_1  | postgresql-repmgr 18:59:29.91 INFO  ==> Starting PostgreSQL in background...
pg-0_1  | postgresql-repmgr 18:59:30.03 INFO  ==> Registering Primary...
pg-0_1  | postgresql-repmgr 18:59:30.32 INFO  ==> Loading custom scripts...
pg-0_1  | postgresql-repmgr 18:59:30.33 INFO  ==> Stopping PostgreSQL...
pg-0_1  | postgresql-repmgr 18:59:31.34 INFO  ==> ** PostgreSQL with Replication Manager setup finished! **
pg-0_1  |
pg-0_1  | postgresql-repmgr 18:59:31.37 INFO  ==> Starting PostgreSQL in background...
pg-0_1  | postgresql-repmgr 18:59:31.48 INFO  ==> ** Starting repmgrd **
pg-0_1  | [2020-09-06 18:59:31] [NOTICE] repmgrd (repmgrd 5.1.0) starting up
pg-0_1  | [2020-09-06 18:59:31] [INFO] connecting to database "user=repmgr password=abc123 host=pg-0 dbname=repmgr port=5432 connect_timeout=5"
pg-0_1  | [2020-09-06 18:59:31] [DEBUG] connecting to: "user=repmgr password=abc123 connect_timeout=5 dbname=repmgr host=pg-0 port=5432 fallback_application_name=repmgr"
pg-0_1  | [2020-09-06 18:59:31] [DEBUG] node id is 1000, upstream node id is -1
pg-0_1  | INFO:  set_repmgrd_pid(): provided pidfile is /opt/bitnami/repmgr/tmp/repmgr.pid
pg-0_1  | [2020-09-06 18:59:31] [NOTICE] starting monitoring of node "pg-0" (ID: 1000)
pg-0_1  | [2020-09-06 18:59:31] [INFO] "connection_check_type" set to "ping"
pg-0_1  | [2020-09-06 18:59:31] [INFO] executing notification command for event "repmgrd_start"
pg-0_1  | [2020-09-06 18:59:31] [DETAIL] command is:
pg-0_1  |   /opt/bitnami/repmgr/events/router.sh 1000 repmgrd_start 1 "2020-09-06 18:59:31.51813+00" "monitoring cluster primary \"pg-0\" (ID: 1000)"
pg-0_1  | [2020-09-06 18:59:31] [NOTICE] monitoring cluster primary "pg-0" (ID: 1000)
```
