### ISSUE TITLE
Cluster replication unstable

### ISSUE THREAD

**Issue by kfirfer** [bitnami/bitnami-docker-postgresql-repmgr#37]
Hello

I tried to setup simple postgre cluster, with the help of helm chart:
bitnami/postgresql-ha:3.7.0

When I RollingUpdate, I getting this :

```
vostro@dev101:~/code/kfirfer/helm-charts$ kubectl logs postgresql-ha-postgresql-1 postgresql
postgresql-repmgr 12:34:02.13 
postgresql-repmgr 12:34:02.13 Welcome to the Bitnami postgresql-repmgr container
postgresql-repmgr 12:34:02.13 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql-repmgr
postgresql-repmgr 12:34:02.14 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql-repmgr/issues
postgresql-repmgr 12:34:02.14 
postgresql-repmgr 12:34:02.15 INFO  ==> ** Starting PostgreSQL with Replication Manager setup **
postgresql-repmgr 12:34:02.16 INFO  ==> Validating settings in REPMGR_* env vars...
postgresql-repmgr 12:34:02.16 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql-repmgr 12:34:02.17 INFO  ==> Querying all partner nodes for common upstream node...
postgresql-repmgr 12:34:02.19 INFO  ==> Preparing PostgreSQL configuration...
postgresql-repmgr 12:34:02.19 INFO  ==> postgresql.conf file not detected. Generating it...
postgresql-repmgr 12:34:02.22 INFO  ==> Preparing repmgr configuration...
postgresql-repmgr 12:34:02.23 INFO  ==> Initializing Repmgr...
postgresql-repmgr 12:34:02.23 INFO  ==> Waiting for primary node...
postgresql-repmgr 12:35:12.33 INFO  ==> Stopping PostgreSQL...
```

This is my override values from the chart:
```
postgresql:
  password: "hidden"

  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/component
                operator: In
                values:
                  - postgresql
          topologyKey: kubernetes.io/hostname
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 2
      memory: 2Gi
  livenessProbe:
    enabled: false

pgpool:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/component
                operator: In
                values:
                  - pgpool
          topologyKey: kubernetes.io/hostname
  resources:
    requests:
      cpu: 50m
      memory: 150Mi
    limits:
      cpu: 1000m
      memory: 1Gi
  livenessProbe:
    timeoutSeconds: 10

metrics:
  enabled: true
  resources:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 50Mi

persistence:
  size: 10Gi

networkPolicy:
  enabled: true
  allowExternal: false
```
