### ISSUE TITLE
Each run standby performs recovery 

### ISSUE THREAD

**Issue by leonidn22** [bitnami/bitnami-docker-postgresql-repmgr#39]
Hi,

My docker_compose :

```
version: '3.1'
services:
  pg-1:
    image: 'allot/postgresql-repmgr:latest'
    ports:
      - '5432'
    environment:
#      - POSTGRESQL_POSTGRES_PASSWORD=admin
      - POSTGRESQL_PASSWORD=''
      - POSTGRESQL_USERNAME=dbadmin
      - POSTGRESQL_PASSWORD=dba12
      - POSTGRESQL_DATABASE=dba12
      - REPMGR_PASSWORD=repmgrpassword
      - REPMGR_PRIMARY_HOST=pg-0
      - REPMGR_PRIMARY_PORT=5432
      - REPMGR_PARTNER_NODES=pg-0,pg-1:5432
      - REPMGR_NODE_NAME=pg-1
      - REPMGR_NODE_NETWORK_NAME=pg-1
      - REPMGR_PORT_NUMBER=5432
      - BITNAMI_DEBUG=true
    volumes:
      - /data002/postgres:/bitnami/postgresql
      - /data002/postgres/conf:/bitnami/postgresql/conf
      - /data002/postgres/logs:/opt/bitnami/postgresql/logs
    network_mode: 'host'
    container_name: "pg-1"
```

After first run of recovery from now each run of standby it performs  recovery.
I suppose it have to be only once.

```
pg-1    | postgresql-repmgr 10:17:28.80 INFO  ==> Preparing repmgr configuration...
pg-1    | postgresql-repmgr 10:17:28.81 DEBUG ==> Node ID: '1001', Rol: 'standby', Primary Node: 'pg-0:5432'
pg-1    | postgresql-repmgr 10:17:28.81 INFO  ==> Initializing Repmgr...
pg-1    | postgresql-repmgr 10:17:28.81 INFO  ==> Waiting for primary node...
pg-1    | postgresql-repmgr 10:17:28.82 DEBUG ==> Wait for schema repmgr.repmgr on 'pg-0:5432', will try 6 times with 10 delay seconds (TIMEOUT=60)
pg-1    | postgresql-repmgr 10:17:28.84 DEBUG ==> Schema repmgr.repmgr exists!
pg-1    | postgresql-repmgr 10:17:28.84 INFO  ==> Cloning data from primary node...
pg-1    | WARNING: following problems with command line parameters detected:
pg-1    |   -D/--pgdata will be ignored if a repmgr configuration file is provided
pg-1    | NOTICE: destination directory "/bitnami/postgresql/data" provided
pg-1    | NOTICE: checking for available walsenders on the source node (2 required)
pg-1    | NOTICE: checking replication connections can be made to the source server (2 required)
pg-1    | WARNING: directory "/bitnami/postgresql/data" exists but is not empty
pg-1    | NOTICE: -F/--force provided - deleting existing data directory "/bitnami/postgresql/data"
pg-1    | NOTICE: starting backup (using pg_basebackup)...
pg-1    | NOTICE: standby clone (using pg_basebackup) complete
pg-1    | NOTICE: you can now start your PostgreSQL server
pg-1    | HINT: for example: pg_ctl -D /bitnami/postgresql/data start
pg-1    | HINT: after starting the server, you need to re-register this standby with "repmgr standby register --force" to update the existing node record
pg-1    | [REPMGR EVENT] Node id: 1001; Event type: standby_clone; Success [1|0]: 1; Time: 2020-09-30 10:17:29.570891+00;  Details: cloned from host "pg-0", port 5432; backup method: pg_basebackup; --force: Y
pg-1    | Looking for the script: /opt/bitnami/repmgr/events/execs/standby_clone.sh
pg-1    | [REPMGR EVENT] no script '/opt/bitnami/repmgr/events/execs/standby_clone.sh' found. Skipping...
pg-1    | postgresql-repmgr 10:17:29.59 INFO  ==> Initializing PostgreSQL database...
pg-1    | postgresql-repmgr 10:17:29.59 INFO  ==> Cleaning stale /bitnami/postgresql/data/standby.signal file
pg-1    | postgresql-repmgr 10:17:29.60 DEBUG ==> Copying files from /bitnami/postgresql/conf to /opt/bitnami/postgresql/conf
pg-1    | postgresql-repmgr 10:17:29.60 INFO  ==> Custom configuration /opt/bitnami/postgresql/conf/postgresql.conf detected
pg-1    | postgresql-repmgr 10:17:29.61 INFO  ==> Custom configuration /opt/bitnami/postgresql/conf/pg_hba.conf detected
pg-1    | postgresql-repmgr 10:17:29.61 DEBUG ==> Ensuring expected directories/files exist...
pg-1    | postgresql-repmgr 10:17:29.63 INFO  ==> Deploying PostgreSQL with persisted data...
pg-1    | postgresql-repmgr 10:17:29.65 INFO  ==> Configuring replication parameters
pg-1    | postgresql-repmgr 10:17:29.67 INFO  ==> Configuring fsync
pg-1    | postgresql-repmgr 10:17:29.69 INFO  ==> Setting up streaming replication slave...
pg-1    | postgresql-repmgr 10:17:29.71 INFO  ==> Starting PostgreSQL in background...
pg-1    | waiting for server to start.... done
pg-1    | server started
pg-1    | postgresql-repmgr 10:17:30.04 INFO  ==> Unregistering standby node...
pg-1    | NOTICE: unregistering node 1001
pg-1    | [REPMGR EVENT] Node id: 1001; Event type: standby_unregister; Success [1|0]: 1; Time: 2020-09-30 10:17:30.088626+00;  Details: 
pg-1    | Looking for the script: /opt/bitnami/repmgr/events/execs/standby_unregister.sh
pg-1    | [REPMGR EVENT] no script '/opt/bitnami/repmgr/events/execs/standby_unregister.sh' found. Skipping...
pg-1    | postgresql-repmgr 10:17:30.10 INFO  ==> Registering Standby node...
pg-1    | NOTICE: using provided configuration file "/opt/bitnami/repmgr/conf/repmgr.conf"
pg-1    | WARNING: --upstream-node-id not supplied, assuming upstream node is primary (node ID 1000)
pg-1    | [REPMGR EVENT] Node id: 1001; Event type: standby_register; Success [1|0]: 1; Time: 2020-09-30 10:17:30.142456+00;  Details: standby registration succeeded; upstream node ID is 1000 (-F/--force option was used)
pg-1    | Looking for the script: /opt/bitnami/repmgr/events/execs/standby_register.sh
pg-1    | [REPMGR EVENT] no script '/opt/bitnami/repmgr/events/execs/standby_register.sh' found. Skipping...
pg-1    | NOTICE: standby node "pg-1" (ID: 1001) successfully registered
pg-1    | postgresql-repmgr 10:17:30.16 INFO  ==> Stopping PostgreSQL...
pg-1    | postgresql-repmgr 10:17:31.17 INFO  ==> ** PostgreSQL with Replication Manager setup finished! **
pg-1    | 
pg-1    | postgresql-repmgr 10:17:31.19 INFO  ==> Starting PostgreSQL in background...
pg-1    | waiting for server to start.... done
pg-1    | server started
pg-1    | postgresql-repmgr 10:17:31.53 INFO  ==> ** Starting repmgrd **
pg-1    | [2020-09-30 10:17:31] [NOTICE] repmgrd (repmgrd 5.1.0) starting up
pg-1    | INFO:  set_repmgrd_pid(): provided pidfile is /opt/bitnami/repmgr/tmp/repmgr.pid
pg-1    | [2020-09-30 10:17:31] [NOTICE] starting monitoring of node "pg-1" (ID: 1001)
