### ISSUE TITLE
how to perform standby switchover?

### ISSUE THREAD

**Issue by leonidn22** [bitnami/bitnami-docker-postgresql-repmgr#56]
I have three nodes running in network_mode : 'host' mode.
After failing pg-0 pg-1 was getting primary

I want to return pg-0 to be primary

Tried:

`docker exec -ti pg-0 /opt/bitnami/scripts/postgresql-repmgr/entrypoint.sh repmgr standby switchover  -f /opt/bitnami/repmgr/conf/repmgr.conf -R root`

And the error:

NOTICE: executing switchover on node "pg-0" (ID: 1000)
WARNING: unable to connect to remote host "pg-1" via SSH
ERROR: unable to connect via SSH to host "pg-1", user "root"

How it's possible to perform switchover?

My docker-compose.yml

```
version: '2'

services:
  pg_rep:
    image: 'allot/postgresql-repmgr:latest'
    restart: unless-stopped
    ports:
      - '5432'
    environment:
      #      - POSTGRESQL_POSTGRES_PASSWORD=admin
      - POSTGRESQL_PASSWORD=''
      - POSTGRESQL_USERNAME=dbadmin
      - POSTGRESQL_PASSWORD=dba12
      - POSTGRESQL_DATABASE=dba12
      - REPMGR_PASSWORD=rep12!
      - REPMGR_PRIMARY_HOST=pg-0
      - REPMGR_PRIMARY_PORT=5432
      - REPMGR_PARTNER_NODES=pg-0,pg-1,pg-2:5432
      - REPMGR_NODE_NAME=pg-0
      - REPMGR_NODE_NETWORK_NAME=pg-0
      - REPMGR_PORT_NUMBER=5432
      - BITNAMI_DEBUG=true
    volumes:
      - /data/postgres:/bitnami/postgresql
      - /data/postgres/conf:/bitnami/postgresql/conf
      - /data/postgres/logs:/opt/bitnami/postgresql/logs
    network_mode: 'host'
    container_name: "pg-0"
```

Thanks in advance
