### ISSUE TITLE
Issue in configuring Auto Failover with bitnami-docker-postgresql-repmgr

### ISSUE THREAD

**Issue by Super17mohit** [bitnami/bitnami-docker-postgresql-repmgr#69]
I have been trying to configure 'Auto-Failover Of Postgresql Database With Docker and Repmgr'

OS:ubuntu 18.4

#docker logs container_name

```bash
postgresql-repmgr 11:25:31.50 Welcome to the Bitnami postgresql-repmgr container
postgresql-repmgr 11:25:31.50 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql-repmgr
postgresql-repmgr 11:25:31.51 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql-repmgr/issues
postgresql-repmgr 11:25:31.51
postgresql-repmgr 11:25:31.54 INFO  ==> ** Starting PostgreSQL with Replication Manager setup **
postgresql-repmgr 11:25:31.57 INFO  ==> Validating settings in REPMGR_* env vars...
postgresql-repmgr 11:25:31.58 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql-repmgr 11:25:31.58 INFO  ==> Querying all partner nodes for common upstream node...
postgresql-repmgr 11:25:31.66 INFO  ==> Preparing PostgreSQL configuration...
postgresql-repmgr 11:25:31.67 INFO  ==> postgresql.conf file not detected. Generating it...
postgresql-repmgr 11:25:31.80 INFO  ==> Preparing repmgr configuration...
postgresql-repmgr 11:25:31.81 INFO  ==> Initializing Repmgr...
postgresql-repmgr 11:25:31.82 INFO  ==> Waiting for primary node...

```
*Version**

- Output of `docker version`:
```
Client:
 Version:           19.03.6
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        369ce74a3c
 Built:             Fri Dec 18 12:21:44 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.6
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       369ce74a3c
  Built:            Thu Dec 10 13:23:49 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.3-0ubuntu1~18.04.4
  GitCommit:
 runc:
  Version:          spec: 1.0.1-dev
  GitCommit:
 docker-init:
  Version:          0.18.0
  GitCommit:

```

- Output of `docker info`:
```
Client:
 Debug Mode: false

Server:
 Containers: 9
  Running: 9
  Paused: 0
  Stopped: 0
 Images: 17
 Server Version: 19.03.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version:
 runc version:
 init version:
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-136-generic
 Operating System: Ubuntu 18.04.5 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.64GiB
 Name: Docker2
 ID: YWVS:REOX:QXF2:OY5N:ZQWG:JBQ4:3X4Q:Z7WC:7YB2:VSTL:QIA5:ZJLN
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

- Output of `docker-compose version` (if applicable):
```
docker-compose version 1.17.1, build unknown
docker-py version: 2.5.1
CPython version: 2.7.17
OpenSSL version: OpenSSL 1.1.1  11 Sep 2018
```

=================
docker-compose-yml

```yaml
version: '2.2'
services:
  db_abuse:
    image: bitnami/postgresql-repmgr:11-debian-10
    container_name: db_abuse
    restart:        always
    environment:
      POSTGRES_USER:     postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB:       abuse_db
      POSTGRESQL_PASSWORD: custompassword
      REPMGR_PASSWORD: repmgrpassword
      REPMGR_PRIMARY_HOST: db_abuse
      REPMGR_NODE_NETWORK_NAME: db_abuse-0
      REPMGR_NODE_ID: db_abuse
      REPMGR_NODE_NAME: db_abuse-0
      REPMGR_PARTNER_NODES: db_abuse-0,db_abuse-1:5433
      REPMGR_PORT_NUMBER: 5433
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - '5433:5432'
    volumes:
      - pg_3_data:/bitnami/postgresql
  db_abuse1:
    image: bitnami/postgresql-repmgr:11-debian-10
    container_name: db_abuse1
    restart:        always
    environment:
      POSTGRES_USER:     postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB:       abuse_db
      POSTGRESQL_PASSWORD: custompassword
      REPMGR_PASSWORD: repmgrpassword
      REPMGR_PRIMARY_HOST: db_abuse
      REPMGR_NODE_ID: db_abuse1
      REPMGR_NODE_NAME: db_abuse-1
      REPMGR_NODE_NETWORK_NAME: db_abuse1
      REPMGR_PARTNER_NODES: db_abuse-0,db_abuse1:5434
      REPMGR_PORT_NUMBER: 5434
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - '5434:5432'
    volumes:
      - pg_4_data:/bitnami/postgresql
  redis_master:
    image: redis:5
    container_name: redis_master
    restart:        always
    ports:
      - '6379:6379'
    volumes:
      - ./redis/redis_master:/data
  redis_slave:
    image: redis:5
    container_name: redis_slave
    restart:        always
    command: redis-server --port 6380 --slaveof redis_master 6379
    ports:
      - '6380:6380'
    volumes:
      - ./redis/redis_slave:/data
  sentinel:
    build: ./sentinel
    container_name: redis_sentinel
    restart:        always
    ports:
      - '26379:26379'
    environment:
      - SENTINEL_NAME=mysentinel
      - HOST_IP=127.0.0.1
    volumes:
      - ./redis/redis_slave:/data

  pg-0:
    image: docker.io/bitnami/postgresql-repmgr:11-debian-10
    ports:
      - 5432
    volumes:
      - pg_0_data:/bitnami/postgresql
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=adminpassword
      - POSTGRESQL_USERNAME=customuser
      - POSTGRESQL_PASSWORD=custompassword
      - POSTGRESQL_DATABASE=customdatabase
      - REPMGR_PASSWORD=repmgrpassword
      - REPMGR_PRIMARY_HOST=pg-0
      - REPMGR_PRIMARY_PORT=5432
      - REPMGR_PARTNER_NODES=pg-0,pg-1:5432
      - REPMGR_NODE_NAME=pg-0
      - REPMGR_NODE_NETWORK_NAME=pg-0
      - REPMGR_PORT_NUMBER=5432
  pg-1:
    image: docker.io/bitnami/postgresql-repmgr:11-debian-10
    ports:
      - 5432
    volumes:
      - pg_1_data:/bitnami/postgresql
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=adminpassword
      - POSTGRESQL_USERNAME=customuser
      - POSTGRESQL_PASSWORD=custompassword
      - POSTGRESQL_DATABASE=customdatabase
      - REPMGR_PASSWORD=repmgrpassword
      - REPMGR_PRIMARY_HOST=pg-0
      - REPMGR_PRIMARY_PORT=5432
      - REPMGR_PARTNER_NODES=pg-0,pg-1:5432
      - REPMGR_NODE_NAME=pg-1
      - REPMGR_NODE_NETWORK_NAME=pg-1
      - REPMGR_PORT_NUMBER=5432
volumes:
  pg_0_data:
    driver: local
  pg_1_data:
    driver: local
  pg_3_data:
    driver: local
  pg_4_data:
    driver: local
```
