### ISSUE TITLE
Cannot create /opt/bitnami/postgresql/logs/postgresql.log: Permission denied

### ISSUE THREAD

**Issue by batchenr** [bitnami/bitnami-docker-postgresql-repmgr#74]
Im trying to install this docker-image on an exsisting DB but, nothing worked.
I tried installing image on an empty /db_data volum and still i get a premmision isuues.

Docker-compose.yml:

```
version: '3'
services:

        postgres-1:
                image: bitnami/postgresql-repmgr:11
                privileged: true
                user: root
                ports:
                     - 5432:5432
                volumes:
                     - /db_data:/bitnami/postgresql
                environment:
                     - POSTGRESQL_POSTGRES_PASSWORD=adminpassword
                     - POSTGRESQL_USERNAME=myuser
                     - POSTGRESQL_PASSWORD=mypassword
                     - REPMGR_PASSWORD=repmgrpassword
                     - REPMGR_PRIMARY_HOST=postgres-1
                     - REPMGR_PARTNER_NODES=postgres-1
                     - REPMGR_NODE_NAME=postgres-1
                     - REPMGR_NODE_NETWORK_NAME=postgres-1
                     - BITNAMI_DEBUG=true

```

docker-compose version:
`1.25.4
`
docker info:
```
Client:
 Debug Mode: false

Server:
 Containers: 6
  Running: 0
  Paused: 0
  Stopped: 6
 Images: 42
 Server Version: 19.03.7
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-135-generic
 Operating System: Ubuntu 18.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 7.767GiB
 Name: ilm1-wh-swarm02
 ID: F6ON:EAVG:YXU6:IIL3:NM7V:B67D:OYC2:RD3J:KSVC:TLU7:BOY2:FHQT
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support

```

docker logs : 

```
postgres-1_1  | postgresql-repmgr 12:55:41.49
postgres-1_1  | postgresql-repmgr 12:55:41.49 Welcome to the Bitnami postgresql-repmgr container
postgres-1_1  | postgresql-repmgr 12:55:41.49 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql-repmgr
postgres-1_1  | postgresql-repmgr 12:55:41.49 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql-repmgr/issues
postgres-1_1  | postgresql-repmgr 12:55:41.49
postgres-1_1  | postgresql-repmgr 12:55:41.50 INFO  ==> ** Starting PostgreSQL with Replication Manager setup **
postgres-1_1  | postgresql-repmgr 12:55:41.52 INFO  ==> Validating settings in REPMGR_* env vars...
postgres-1_1  | postgresql-repmgr 12:55:41.52 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgres-1_1  | postgresql-repmgr 12:55:41.53 INFO  ==> Querying all partner nodes for common upstream node...
postgres-1_1  | postgresql-repmgr 12:55:41.53 DEBUG ==> Checking node 'postgres-1:5432'...
postgres-1_1  | postgresql-repmgr 12:55:41.54 DEBUG ==> Executing SQL command:
postgres-1_1  | SELECT conninfo FROM repmgr.show_nodes WHERE (upstream_node_name IS NULL OR upstream_node_name = '') AND active=true
postgres-1_1  | psql: could not connect to server: Connection refused
postgres-1_1  |         Is the server running on host "postgres-1" (172.21.0.2) and accepting
postgres-1_1  |         TCP/IP connections on port 5432?
postgres-1_1  | postgresql-repmgr 12:55:41.55 DEBUG ==> Skipping: failed to get primary from the node 'postgres-1:5432'!
postgres-1_1  | postgresql-repmgr 12:55:41.55 INFO  ==> There are no nodes with primary role. Assuming the primary role...
postgres-1_1  | postgresql-repmgr 12:55:41.69 INFO  ==> Preparing PostgreSQL configuration...
postgres-1_1  | postgresql-repmgr 12:55:41.70 DEBUG ==> Injecting a new postgresql.conf file...
postgres-1_1  | postgresql-repmgr 12:55:41.70 INFO  ==> postgresql.conf file not detected. Generating it...
postgres-1_1  | postgresql-repmgr 12:55:41.75 DEBUG ==> Injecting a new pg_hba.conf file...
postgres-1_1  | postgresql-repmgr 12:55:41.76 INFO  ==> Preparing repmgr configuration...
postgres-1_1  | postgresql-repmgr 12:55:41.76 DEBUG ==> Node ID: '1001', Rol: 'primary', Primary Node: ':5432'
postgres-1_1  | postgresql-repmgr 12:55:41.76 INFO  ==> Initializing Repmgr...
postgres-1_1  | postgresql-repmgr 12:55:41.77 INFO  ==> Initializing PostgreSQL database...
postgres-1_1  | postgresql-repmgr 12:55:41.77 DEBUG ==> Copying files from /bitnami/postgresql/conf to /opt/bitnami/postgresql/conf
postgres-1_1  | postgresql-repmgr 12:55:41.77 INFO  ==> Custom configuration /opt/bitnami/postgresql/conf/postgresql.conf detected
postgres-1_1  | postgresql-repmgr 12:55:41.77 INFO  ==> Custom configuration /opt/bitnami/postgresql/conf/pg_hba.conf detected
postgres-1_1  | postgresql-repmgr 12:55:41.78 DEBUG ==> Ensuring expected directories/files exist...
postgres-1_1  | postgresql-repmgr 12:55:41.81 INFO  ==> Deploying PostgreSQL with persisted data...
postgres-1_1  | postgresql-repmgr 12:55:41.83 INFO  ==> Configuring replication parameters
postgres-1_1  | postgresql-repmgr 12:55:41.85 INFO  ==> Configuring fsync
postgres-1_1  | postgresql-repmgr 12:55:41.86 DEBUG ==> Skipping repmgr configuration...
postgres-1_1  | postgresql-repmgr 12:55:41.86 INFO  ==> ** PostgreSQL with Replication Manager setup finished! **
postgres-1_1  |
postgres-1_1  | postgresql-repmgr 12:55:41.88 INFO  ==> Starting PostgreSQL in background...
postgres-1_1  | waiting for server to start..../bin/sh: 1: cannot create /opt/bitnami/postgresql/logs/postgresql.log: Permission denied
postgres-1_1  |  stopped waiting
postgres-1_1  | pg_ctl: could not start server
postgres-1_1  | Examine the log output.
api_postgres-1_1 exited with code 1

```
Also tried `chown -R 1001:1001 /db_data`

If i remove "user: root" from docker-compose i get:
```
postgres-1_1  | postgresql-repmgr 12:59:52.05 DEBUG ==> Ensuring expected directories/files exist...
postgres-1_1  | chmod: changing permissions of '/bitnami/postgresql/data': Operation not permitted
postgres-1_1  | postgresql-repmgr 12:59:52.06 WARN  ==> Lack of permissions on data directory!
postgres-1_1  | chmod: changing permissions of '/bitnami/postgresql/data': Operation not permitted
postgres-1_1  | postgresql-repmgr 12:59:52.06 WARN  ==> Lack of permissions on data directory!
postgres-1_1  | ls: cannot open directory '/bitnami/postgresql/data': Permission denied
postgres-1_1  | The files belonging to this database system will be owned by user "postgres".
postgres-1_1  | This user must also own the server process.
postgres-1_1  |
postgres-1_1  | The database cluster will be initialized with locale "en_US.UTF-8".
postgres-1_1  | The default text search configuration will be set to "english".
postgres-1_1  |
postgres-1_1  | Data page checksums are disabled.
postgres-1_1  |
postgres-1_1  | initdb: could not access directory "/bitnami/postgresql/data": Permission denied
api_postgres-1_1 exited with code 1

```

**Comment by alemorcuq** [comment]
Hi, @batchenr.

I can't reproduce your issue. This is the `docker-compose.yml` file I'm using (it's the same one you shared without setting the user to root):

```
❯ cat docker-compose.yml
version: '3'
services:

        postgres-1:
                image: bitnami/postgresql-repmgr:11
                ports:
                     - 5432:5432
                volumes:
                     - /db_data:/bitnami/postgresql
                environment:
                     - POSTGRESQL_POSTGRES_PASSWORD=adminpassword
                     - POSTGRESQL_USERNAME=myuser
                     - POSTGRESQL_PASSWORD=mypassword
                     - REPMGR_PASSWORD=repmgrpassword
                     - REPMGR_PRIMARY_HOST=postgres-1
                     - REPMGR_PARTNER_NODES=postgres-1
                     - REPMGR_NODE_NAME=postgres-1
                     - REPMGR_NODE_NETWORK_NAME=postgres-1
                     - BITNAMI_DEBUG=true
```

I create the directory for the volume as follows:

```
❯ sudo mkdir /db_data

❯ sudo chown -R 1001:1001 /db_data

❯ ls -la /db_data
total 8.0K
drwxr-xr-x 2 1001 1001 4.0K 2021-06-07 07:29 ./
drwxr-xr-x 1 root root 4.0K 2021-06-07 07:29 ../
```

And then I run `docker-compose up` and the server starts:

```
...
postgres-1_1  | server started
postgres-1_1  | postgresql-repmgr 07:29:37.39 INFO  ==> ** Starting repmgrd **
postgres-1_1  | [2021-06-07 07:29:37] [NOTICE] repmgrd (repmgrd 5.2.1) starting up
postgres-1_1  | INFO:  set_repmgrd_pid(): provided pidfile is /opt/bitnami/repmgr/tmp/repmgr.pid
postgres-1_1  | [2021-06-07 07:29:37] [NOTICE] starting monitoring of node "postgres-1" (ID: 1001)
postgres-1_1  | [2021-06-07 07:29:37] [NOTICE] monitoring cluster primary "postgres-1" (ID: 1001)
```
