### ISSUE TITLE
Kubernetes psql doesn't save query history

### ISSUE THREAD

**Issue by batchenr** [bitnami/bitnami-docker-postgresql-repmgr#88]
Im using Kubenetes kubectl `Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2" ` And have `bitnami/postgresql-repmgr:11` pod, unlike docker container when i ran querys,
If i reconnect to the container again when i press arrow up i can see the last query i ran,
on the kubernetes pod i cant , it does nothing  - is there a way to make it show the history like docker? 
Psql depl.yaml :

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert --volumes hostPath
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: postgres-2
  name: postgres-2
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: postgres-2
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert --volumes hostPath
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: postgres-2
    spec:
      containers:
      - env:
        - name: BITNAMI_DEBUG
          value: "true"
        - name: POSTGRESQL_PASSWORD
          value: password
        - name: POSTGRESQL_POSTGRES_PASSWORD
          value: admin
        - name: POSTGRESQL_USERNAME
          value: user
        - name: REPMGR_NODE_NAME
          value: postgres-2
        - name: REPMGR_NODE_NETWORK_NAME
          value: postgres-2
        - name: REPMGR_PARTNER_NODES
          value: postgres-1,postgres-2:5432
        - name: REPMGR_PASSWORD
          value: rpassword
        - name: REPMGR_PGHBA_TRUST_ALL
          value: "yes"
        - name: REPMGR_PRIMARY_HOST
          value: postgres-1
        - name: REPMGR_PRIMARY_PORT
          value: "5432"
        image: bitnami/postgresql-repmgr:11
        imagePullPolicy: ""
        name: postgres-2
        ports:
        - containerPort: 5432
        resources: {}
        volumeMounts:
        - mountPath: /bitnami/postgresql
          name: postgres-2-hostpath0
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - hostPath:
          path: /db5_data
        name: postgres-2-hostpath0
status: {}

```
